"""empty message

Revision ID: 809103402554
Revises: 8bf52cc8b14a
Create Date: 2023-08-12 17:46:09.502642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809103402554'
down_revision = '8bf52cc8b14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
