"""empty message

Revision ID: afed2f0bb1f6
Revises: ba85f662fc0b
Create Date: 2023-08-13 20:37:59.814330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afed2f0bb1f6'
down_revision = 'ba85f662fc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('categories',
               existing_type=sa.VARCHAR(length=604),
               type_=sa.String(length=204),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('categories',
               existing_type=sa.String(length=204),
               type_=sa.VARCHAR(length=604),
               existing_nullable=True)

    # ### end Alembic commands ###
