"""empty message

Revision ID: b5ada99280ea
Revises: bc83593426ef
Create Date: 2023-08-14 15:57:42.078870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ada99280ea'
down_revision = 'bc83593426ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waste_level', sa.String(length=400), nullable=True))
        batch_op.drop_column('waste')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waste', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
        batch_op.drop_column('waste_level')

    # ### end Alembic commands ###
